### ISSUE TITLE
 broccoliBuilderErrorStack … Can't resolve '../../test-waiters'

### ISSUE THREAD

**Issue by muziejus** [embroider-build/embroider#778]
I can't tell if this is related to [this issue](https://github.com/emberjs/ember-test-waiters/issues/158), but I thought I'd give embroider a try and I get a build failure on step 1 ("First make it work with no options. This is the mode that supports maximum backward compatibility."):

`  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve '../../test-waiters' in '$TMPDIR/embroider/6d8b07/node_modules/@ember/test-helpers/-internal/debug-info.js'
`

This is with Ember 3.23.1

**Comment by angelayanpan** [comment]
is anyone looking into this?

**Comment by ef4** [comment]
@rwjblue mentioned an issue recently with the way that `@ember/test-waiters` tries to deduplicate itself not playing well with Embroider.

If you use something like yarn resolutions to force your app to have a single copy of `@ember/test-waiters`, does that workaround the problem?

**Comment by angelayanpan** [comment]
my addon doesn't have ember/test-waiters in package.json

from yarn.lock,  I see there are ^3.0.0 and ^2.4.3 

which version should my addon try to resolve to?

**Comment by angelayanpan** [comment]
`yarn why @ember/test-waiters
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@ember/test-waiters"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@ember/test-waiters@2.4.5"
info Reasons this module exists
   - "@linkedin#ember-cli-pemberly-tracking" depends on it
   - Hoisted from "@linkedin#ember-cli-pemberly-tracking#@ember#test-waiters"
info Disk size without dependencies: "232KB"
info Disk size with unique dependencies: "3.19MB"
info Disk size with transitive dependencies: "50.08MB"
info Number of shared dependencies: 175
=> Found "@ember/test-helpers#@ember/test-waiters@3.0.0"
info This module exists because "@ember#test-helpers" depends on it.
info Disk size without dependencies: "156KB"
info Disk size with unique dependencies: "1.18MB"
info Disk size with transitive dependencies: "46.15MB"
info Number of shared dependencies: 157

**Comment by nightire** [comment]
@angelayanpan I can confirm to add a resolution entry in the root `package.json` will fix this issue:

```json
"resolutions": {
  "@ember/test-waiters": "3.0.1"
}
```

**Comment by angelayanpan** [comment]
thanks! but this is not a permanent solution right?

**Comment by ef4** [comment]
I think this is fixed by https://github.com/embroider-build/embroider/pull/1064

**Comment by angelayanpan** [comment]
when do you plan to release the above PR?

**Comment by bertdeblock** [comment]
It's already released I think: https://github.com/embroider-build/embroider/blob/master/CHANGELOG.md#v0500-2022-01-08

**Comment by angelayanpan** [comment]
ok, so I have pulled in 
    "@embroider/compat": "^0.50.0",
    "@embroider/core": "^0.50.0",
    "@embroider/test-setup": "^0.50.0",
    "@embroider/webpack": "^0.50.0",
    
I still see can't resolve test-waiter in my project.

**Comment by ef4** [comment]
Yes, the PR I mentioned above is released on 0.50. This issue may be a combination of people reporting two different problems that interact, and only one of them is fixed.

@angelayanpan is your stack trace still exactly the same as the ones above?

Is the place that's failing to find test-waiters using it via the old import path (`ember-test-waiters`) or the modern one (`@ember/test-waiters`)?

**Comment by rwjblue** [comment]
@angelayanpan - This is after updating to @embroider/* 0.50.0?

**Comment by angelayanpan** [comment]
yes @rwjblue

**Comment by roomman** [comment]
Similar situation here. Added @ember/test-waiters to a project with  @embroider/* 0.50.2 and getting the following:
```
ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve '@ember/test-waiters' in '/private/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/embroider/b26e50/authenticators'
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/simon/Sites/oneday-academy-ui/node_modules/neo-async/async.js:6883:13
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve '@ember/test-waiters' in '$TMPDIR/embroider/b26e50/authenticators/oneday-firebase.js'
  - errorMessage: authenticators/oneday-firebase.js: Module not found: Error: Can't resolve '@ember/test-waiters' in '$TMPDIR/embroider/b26e50/authenticators/oneday-firebase.js'
        at PackagerRunner (@embroider/webpack)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: authenticators/oneday-firebase.js
    - line: [null]
    - treeDir: [undefined]
  - message: authenticators/oneday-firebase.js: Module not found: Error: Can't resolve '@ember/test-waiters' in '$TMPDIR/embroider/b26e50/authenticators/oneday-firebase.js'
        at PackagerRunner (@embroider/webpack)
  - name: Error
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve '@ember/test-waiters' in '$TMPDIR/embroider/b26e50/authenticators/oneday-firebase.js'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve '@ember/test-waiters' in '/private/var/folders/cp/mp10cjhd1xdf8wg5gk7s9g500000gn/T/embroider/b26e50/authenticators'
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/simon/Sites/oneday-academy-ui/node_modules/neo-async/async.js:6883:13
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/simon/Sites/oneday-academy-ui/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)

=================================================================================

```

**Comment by angelayanpan** [comment]
you probably need add to the `resolutions` mentioned above.

**Comment by roomman** [comment]
Thanks @angelayanpan but this particular project doesn't use Yarn so that's not an option, unless I've missed some recent NPM feature releases?

**Comment by vfuto** [comment]
@roomman I had the same issue, build failed with adding `"@ember/test-waiters": "3.0.1"` in resolutions, but after cleaning `node_modules` (also deleted the build from `$TMPDIR/embroider`) and running `yarn install` fixed it.
